[pre-commit]
parallel = true

[pre-commit.commands.actionlint]
run = "mise exec -- actionlint {staged_files}"
glob = [".github/workflows/*.yml", ".github/workflows/*.yaml"]

[pre-commit.commands.format-yaml]
run = "mise exec -- yamlfmt {staged_files}"
glob = ["**/*.yaml", "**/*.yml"]
stage_fixed = true

[pre-commit.commands.gitleaks]
run = "mise exec -- gitleaks protect --staged --redact"

[pre-commit.commands.yamllint]
run = "mise exec -- yamllint {staged_files}"
glob = ["**/*.yaml", "**/*.yml"]

[pre-commit.commands.zizmor]
run = "mise exec -- zizmor {staged_files}"
glob = [".github/workflows/*.yml", ".github/workflows/*.yaml"]

[pre-commit.commands.dprint]
run = "mise exec -- dprint fmt {staged_files}"
glob = ["**/*.md"]
stage_fixed = true

[pre-commit.commands.python-tests]
run = "task ci"
glob = ["*.py", "src/**/*.py", "scripts/**/*.py", "tests/**/*.py"]

[commit-msg.commands.cocogitto]
run = "mise exec -- cog verify \"$(cat {1})\""
