---
name: Auto-fix formatting

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: autofix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/autofix.yml@998ff283c3a431bbcb74421180121826cca8fdd7 # v1.4.0
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.22"
      autofix-config-dir: .
      autofix-shfmt: false
