---
name: Auto-fix formatting

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: autofix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/autofix.yml@783a7a3a03ae71efcdf5b13eaea80efe26dfa641 # v2.2.0
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.7.12"
      autofix-config-dir: .
      autofix-shfmt: false
