---
name: Auto-fix formatting

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: autofix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/autofix.yml@7f2abdd838a855dba31a2b2de6358529fdcef09d # v1.8.0
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.6.5"
      autofix-config-dir: .
      autofix-shfmt: false
