---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@7f2abdd838a855dba31a2b2de6358529fdcef09d # v1.8.0
    permissions:
      contents: write
      pull-requests: write
