---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@7d7ddabef968d8505aceb8a1f8965afd872f0a0c # v2.4.0
    permissions:
      contents: write
      pull-requests: write
