---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: config-sync
  cancel-in-progress: false

jobs:
  sync:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@v1.6.1
    permissions:
      contents: write
      pull-requests: write
