---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: label-sync
  cancel-in-progress: false

jobs:
  label-sync:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@7f2abdd838a855dba31a2b2de6358529fdcef09d # v1.8.0
    permissions:
      contents: read
      issues: write
