---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: label-sync
  cancel-in-progress: false

jobs:
  label-sync:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@0d0f448de257f354c89dc3a128871235d6ba8c11 # v2.5.0
    permissions:
      contents: read
      issues: write
