---
name: Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    # renovate: datasource=github-tags depName=DevSecNinja/.github
    uses: DevSecNinja/.github/.github/workflows/lint.yml@998ff283c3a431bbcb74421180121826cca8fdd7 # v1.4.0
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.5.9"
      lint-config-dir: .
      lint-config-drift: false
      lint-shellcheck: false
      lint-shfmt: false
      lint-checkov: false
      lint-trivy: false
